
osx_image: xcode12
language: swift
xcode_workspace: DFramework.xcworkspace
xcode_destination: platform=iOS Simulator,name=iPhone 11
podfile: Podfile

before_install:
- brew update
- pod install

jobs:
  include:
    - name: 'Build & Test Example'
      xcode_scheme: DFramework
    - name: 'Pod library lint'
      script:
      - pod lib lint DFramework.podspec

notifications:
  slack: demirciy:pzu0mBJfP9CAy16arOxASvjF
  email:
    recipients:
      - demirciy.software@gmail.com
    on_success: never
    on_failure: always
